<a href="https://colab.research.google.com/github/manumanasa1205/Gen-AI-project/blob/main/NumPy_Notes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##NumPy (Numerical Python) is a fundamental library for numerical computations in Python. It provides support for arrays, matrices, and many mathematical functions.

##Installation

In [107]:
pip install numpy

##Importing NumPy

In [108]:
import numpy as np

##Creating Arrays

In [109]:
xyz = np.array([1, 2, 3, 4, 5])
xyz

array([1, 2, 3, 4, 5])

In [110]:
arr_2d = np.array([[1,2,3],[4,5,6]])
arr_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [111]:
zeros_arr = np.zeros((3, 3))  # 3x3 array of zeros
zeros_arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [112]:
ones_arr = np.ones((2, 4))  # 2x4 array of ones
ones_arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
identity_matrix = np.eye(3)  # 3x3 identity matrix
identity_matrix

In [ ]:
range_arr = np.arange(0, 10, 2)  # [0, 2, 4, 6, 8]
range_arr

In [113]:
linspace_arr = np.linspace(0, 100, 5)  # [0.0, 0.25, 0.5, 0.75, 1.0]
linspace_arr

array([  0.,  25.,  50.,  75., 100.])

In [ ]:
random_arr = np.random.rand(2, 3)  # 2x3 array of random values between 0 and 1
random_arr

##Array Attributes

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr

In [ ]:
arr.shape  # Returns the dimensions of the array (rows, columns)

In [ ]:
arr.dtype  # Returns the data type of the array (e.g., int64, float64)

In [ ]:
arr.size  # Total number of elements in the array

In [ ]:
arr.ndim  # Number of dimensions (axes) of the array

In [ ]:
#arr.reshape(rows, cols)  # Reshapes the array
arr.reshape(2,3)

In [ ]:
arr.T  # Transposes the array

In [ ]:
arr.flatten()  # Converts a multi-dimensional array to 1D

In [ ]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([4,5,6])

In [ ]:
np.concatenate((arr1, arr2),axis=0)  # Concatenates arrays along a specified axis

In [ ]:
#np.split(arr, indices)  # Splits an array into sub-arrays

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6])
sub_arrays = np.split(arr, [3, 5])
sub_arrays

In [ ]:
for i, sub_arr in enumerate(sub_arrays):
    print(f"Sub-array {i+1}: {sub_arr}")

##Statistical Operations

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(np.sum(arr))  # Sum of all elements
print(np.mean(arr))  # Mean
print(np.median(arr))  # Median
print(np.std(arr))  # Standard deviation
print(np.var(arr))  # Variance
print(np.min(arr))  # Minimum value
print(np.max(arr))  # Maximum value
print(np.argmax(arr))  # Index of max value
print(np.argmin(arr))  # Index of min value


## Mathematical Operations

Element-wise Operations

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

In [ ]:
print(arr + 2)  # Adds 2 to each element
print(arr - 2)  # subtract 2 from each element
print(arr * 3)  # Multiplies each element by 3
print(arr / 2)  # Divides each element by 2

Matrix Multiplication

In [ ]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

In [ ]:
np.dot(arr1, arr2)  # Dot product of two arrays
arr1 @ arr2  # Alternative syntax for matrix multiplication

In [ ]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print(np.dot(A, B))  # Matrix multiplication
print(A @ B)  # Alternative for matrix multiplication
print(np.transpose(A))  # Transpose of a matrix
print(np.linalg.inv(A))  # Inverse of matrix--->inverse of A=1/det(A)*[d -b
    #                                                     -c a ]
print(np.linalg.det(A))# Determinant of matrix--->det=ad-bc

 Sum, Min, Max

In [ ]:
arr = np.array([2,3,4,5,6,10])
arr

In [ ]:
np.sum(arr)  # Sum of all elements

In [ ]:
np.max(arr)  # Maximum value in the array

In [ ]:
np.min(arr)  # Minimum value in the array

 Mean, Median, Standard Deviation

In [ ]:
np.mean(arr)  # Mean of the array

In [ ]:
np.median(arr)  # Median of the array

In [ ]:
np.std(arr)  # Standard deviation of the array

Trigonometric Functions

In [ ]:
np.sin(arr)  # Sine of each element

In [ ]:
np.cos(arr)  # Cosine of each element

In [ ]:
np.tan(arr)  # Tangent of each element

##Indexing and Slicing

Single Element

In [ ]:
arr = np.array([[2,3,4],[5,6,10]])
arr

In [ ]:
arr[0]  # First element of the array


In [ ]:
arr[1, 2]  # Element at row 1, column 2

 Slicing

In [ ]:
arr[1:4]  # Elements from index 1 to 3

In [ ]:
arr[:, 2]  # All rows, column 2

In [ ]:
arr = np.array([[2,3,4],[5,6,10]])
arr

In [ ]:
arr[:2, 0:1]  # Subarray from rows 1-2 and columns 0-1

Boolean Indexing

In [ ]:
arr[arr > 5]  # Elements greater than 2

##Array Manipulation

Stacking

In [ ]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

In [ ]:
np.vstack((arr1, arr2))  # Vertical stacking

In [ ]:
np.hstack((arr1, arr2))  # Horizontal stacking

Copying

In [ ]:
arr = np.array([[2,3,4],[5,6,10]])

In [ ]:
arr_copy = arr.copy()  # Creates a copy of the array
arr_copy

 Sorting

In [ ]:
np.sort(arr)  # Sorts the array

In [ ]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6]])

print(np.concatenate((arr1, arr2.T), axis=1))  # Column-wise concatenation
print(np.vstack((arr1, arr2)))  # Stack vertically
print(np.hstack((arr1, arr2.T)))  # Stack horizontally


##Advanced Operations

Broadcasting

In [ ]:
arr = np.array([[2,3,4],[5,6,10]])
arr

In [ ]:
arr + np.array([1, 2, 3])  # Adds [1, 2, 3] to each row

Masking

In [ ]:
mask = arr > 2
arr[mask]  # Returns elements where the condition is True

Universal Functions (ufuncs)
python

In [ ]:
np.sqrt(arr)  # Square root of each element

In [ ]:
np.exp(arr)  # Exponential of each element

In [ ]:
np.log(arr)  # Natural logarithm of each element

##Saving and Loading Arrays

Saving

In [ ]:
np.save('filename.npy', arr)  # Saves array to a file

Loading

In [ ]:
arr = np.load('filename.npy')  # Loads array from a file
arr

Text Files

In [ ]:
np.savetxt('filename.txt', arr)  # Saves array to a text file
arr = np.loadtxt('filename.txt')  # Loads array from a text file

In [ ]:
arr

##Common Errors and Debugging

Shape Mismatch: Ensure arrays have compatible shapes for operations.

Data Type Issues: Use arr.astype(dtype) to change data types.

Memory Errors: Use np.delete(arr, obj) to remove elements.






##Handling NaN and Infinite Values

In [ ]:
arr = np.array([1, 2, np.nan, 4, np.inf])

print(np.isnan(arr))  # Check for NaN values
print(np.isinf(arr))  # Check for infinite values
print(np.nan_to_num(arr))  # Replace NaN with 0 and Inf with large numbers


##NumPy Advanced Functions

Unique Elements & Counting

In [ ]:
arr = np.array([1, 2, 2, 3, 4, 4, 4, 5])

print(np.unique(arr))  # Get unique elements
print(np.bincount(arr))  # Count occurrences of each integer


Where Condition

In [ ]:
arr = np.array([10, 20, 30, 40])
print(np.where(arr > 20, "High", "Low"))  # Replace values based on condition


Cumulative Sum and Product

In [ ]:
arr = np.array([1, 2, 3, 4])

print(np.cumsum(arr))  # Cumulative sum
print(np.cumprod(arr))  # Cumulative product
